[connections.default]
warehouse = "QUICKSTART_WH"
role = "ACCOUNTADMIN"
database = "QUICKSTART_COMMON"
schema = "PUBLIC"
account = "TWRMRQS-FN39200"
user = "ANDANG"
password = "SnowflakeMetrodata.123"
